Repository gisce/crm_poweremail, pull requests merged in 2018-09, with the labels that each got.

#44 Stop filtering FW/RE text from emails on CRM.CASE
  poweremail_mailbox.py
Labels: To Be Merged, enhancement

#47 Fix bugs: Init, forward and email getting
  crm.py
  crm_data.xml
  poweremail_mailbox.py
Labels: To Be Merged, bug

#48 ADD User and Partner emails on Case.Emails_CC
  crm.py
Labels: To Be Merged, enhancement

#43 "Parsing" a Markdown al enviar
  crm.py
  requirements.txt
Labels: To Be Merged, enhancement, feature

#49 Add to watchers when updating from email
  crm.py
  crm_view.xml
  poweremail_mailbox.py
Labels: enhancement

#50 Fix reading case with ID instead of List
  poweremail_mailbox.py
Labels: To Be Merged, bug
